#!/usr/bin/env bash
#
# AINAP インストールスクリプト
# ConoHa VPS 512MB / Ubuntu 24.04 LTS 専用
#
set -euo pipefail

INSTALL_DIR="/opt/ainap"
SERVICE_USER="ainap"

# 色付き出力
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# =============================================================
# 前提チェック
# =============================================================
if [[ $EUID -ne 0 ]]; then
    error "root 権限で実行してください: sudo bash install.sh"
    exit 1
fi

if ! grep -qi 'ubuntu' /etc/os-release 2>/dev/null; then
    warn "Ubuntu 以外のディストリビューションでの動作は未検証です"
fi

info "===== AINAP インストーラ ====="

# =============================================================
# 1. システムパッケージ
# =============================================================
info "システムパッケージをインストール中..."
apt-get update -qq
apt-get install -y -qq python3-venv python3-pip msmtp git

# =============================================================
# 2. 専用ユーザー作成
# =============================================================
if id "$SERVICE_USER" &>/dev/null; then
    info "ユーザー '$SERVICE_USER' は既に存在します"
else
    info "ユーザー '$SERVICE_USER' を作成中..."
    useradd -r -m -d "$INSTALL_DIR" -s /bin/bash "$SERVICE_USER"
fi

# =============================================================
# 3. プロジェクトデプロイ
# =============================================================
if [[ -d "$INSTALL_DIR/.git" ]]; then
    info "既存インストールを検出。更新します..."
    cd "$INSTALL_DIR"
    sudo -u "$SERVICE_USER" git pull || true
else
    info "プロジェクトをデプロイ中..."
    # ソースファイルをコピー（git clone の代わりにローカルコピー）
    if [[ -d "/home/user/AIAutoWordPress/.git" ]]; then
        # 開発環境からコピー
        mkdir -p "$INSTALL_DIR"
        cp -r /home/user/AIAutoWordPress/{src,config,systemd,pyproject.toml,Makefile} "$INSTALL_DIR/"
        mkdir -p "$INSTALL_DIR"/{data/queue,logs}
        chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
    else
        echo ""
        read -rp "Git リポジトリ URL を入力してください: " REPO_URL
        sudo -u "$SERVICE_USER" git clone "$REPO_URL" "$INSTALL_DIR"
    fi
fi

# =============================================================
# 4. Python 仮想環境
# =============================================================
info "Python 仮想環境をセットアップ中..."
cd "$INSTALL_DIR"
sudo -u "$SERVICE_USER" python3 -m venv venv
sudo -u "$SERVICE_USER" venv/bin/pip install --upgrade pip -q
sudo -u "$SERVICE_USER" venv/bin/pip install -e . -q

# =============================================================
# 5. 環境変数の対話入力
# =============================================================
ENV_FILE="$INSTALL_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
    warn ".env ファイルが既に存在します。上書きしますか？"
    read -rp "[y/N]: " OVERWRITE
    if [[ "$OVERWRITE" != "y" && "$OVERWRITE" != "Y" ]]; then
        info ".env の設定をスキップします"
        SKIP_ENV=true
    fi
fi

if [[ "${SKIP_ENV:-}" != "true" ]]; then
    info "=== 環境変数の設定 ==="
    echo ""

    # Claude API
    read -rp "Anthropic API Key (sk-ant-api03-...): " ANTHROPIC_API_KEY

    # WordPress
    echo ""
    info "--- WordPress 設定 ---"
    read -rp "WordPress サイトURL (https://example.com): " WP_BASE_URL
    read -rp "WordPress ユーザー名: " WP_USERNAME
    read -rp "WordPress Application Password: " WP_APP_PASSWORD

    # SMTP
    echo ""
    info "--- メール通知設定 ---"
    read -rp "SMTP ホスト [smtp.gmail.com]: " SMTP_HOST
    SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
    read -rp "SMTP ポート [587]: " SMTP_PORT
    SMTP_PORT=${SMTP_PORT:-587}
    read -rp "SMTP ユーザー (メールアドレス): " SMTP_USER
    read -rp "SMTP パスワード (アプリパスワード推奨): " SMTP_PASSWORD
    read -rp "通知先メールアドレス: " NOTIFY_EMAIL

    cat > "$ENV_FILE" <<ENVEOF
# ===== AINAP Environment Variables =====
# Generated by install.sh on $(date)

# --- Claude API ---
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# --- WordPress ---
WP_BASE_URL=${WP_BASE_URL}
WP_USERNAME=${WP_USERNAME}
WP_APP_PASSWORD=${WP_APP_PASSWORD}

# --- SMTP (msmtp) ---
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASSWORD=${SMTP_PASSWORD}
NOTIFY_EMAIL=${NOTIFY_EMAIL}
ENVEOF

    chown "$SERVICE_USER:$SERVICE_USER" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    info ".env ファイルを作成しました (chmod 600)"
fi

# =============================================================
# 6. msmtp 設定
# =============================================================
if [[ "${SKIP_ENV:-}" != "true" ]]; then
    info "msmtp を設定中..."
    MSMTP_CONF="/etc/msmtprc"
    cat > "$MSMTP_CONF" <<MSMTPEOF
# AINAP msmtp configuration
defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp.log

account        default
host           ${SMTP_HOST}
port           ${SMTP_PORT}
from           ${SMTP_USER}
user           ${SMTP_USER}
password       ${SMTP_PASSWORD}
MSMTPEOF

    chmod 600 "$MSMTP_CONF"
    info "msmtp 設定完了: $MSMTP_CONF"
fi

# =============================================================
# 7. systemd ユニット登録
# =============================================================
info "systemd ユニットを登録中..."
cp "$INSTALL_DIR/systemd/ainap.service" /etc/systemd/system/
cp "$INSTALL_DIR/systemd/ainap.timer" /etc/systemd/system/
systemctl daemon-reload
systemctl enable ainap.timer
systemctl start ainap.timer

info "systemd timer を有効化しました"

# =============================================================
# 8. ディレクトリ権限
# =============================================================
info "パーミッションを設定中..."
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
chmod 755 "$INSTALL_DIR"
chmod -R 750 "$INSTALL_DIR/data"
chmod -R 750 "$INSTALL_DIR/logs"

# =============================================================
# 9. 動作確認
# =============================================================
info ""
info "===== インストール完了 ====="
info ""
info "次のコマンドで動作確認できます:"
info "  sudo systemctl start ainap.service    # 即時実行"
info "  sudo journalctl -u ainap.service -f   # ログ確認"
info "  sudo systemctl status ainap.timer     # タイマー状態"
info ""
info "スケジュール: 毎日 7:00, 10:00, 13:00, 17:00, 21:00 (JST)"
info ""

# テスト実行（オプション）
echo ""
read -rp "テスト実行しますか？ [y/N]: " RUN_TEST
if [[ "$RUN_TEST" == "y" || "$RUN_TEST" == "Y" ]]; then
    info "テスト実行中..."
    sudo -u "$SERVICE_USER" bash -c "cd $INSTALL_DIR && venv/bin/python -m pytest tests/ -v" || warn "テスト失敗"
fi
